### ISSUE TITLE
Waveform fit plots do not show window length

### ISSUE THREAD

**Issue by shicks-seismo** [pyrocko/grond#3]
Hi,
The waveform fits shown in the summary produced by `grond report` do not show the length of the time window.

Fig. 4 of Dahm et al. (2018, J.Seismol.) shows the "delta = _x_ s " labels, but these labels are not shown by the version of Grond I am running. Also, the start times are not shown for all waveforms.

To be sure, I just pulled and installed the latest version of Grond from the repository.

Waveform image attached. 
Incidentally, the fits are beautiful (especially given these are ocean-bottom data)!

[fits_waveform default fig_td love_z_0_0 d100](https://user-images.githubusercontent.com/25796081/46347028-0c38f280-c642-11e8-8071-f27736ac2494.png)
!

**Comment by emolch** [comment]
Yes, we have also noticed this problem. My plan is to additionally split the figures into individual image files, so that the HTML of the report can take care of how the subplots are arranged. This would also improve how the search in the report works. But -- I cannot fix this before Friday, unfortunately.

**Comment by emolch** [comment]
done in d8f111bac4c64a1fcc11c102c2fde079ee8ccc0e
